//
//  MockActivityService.swift
//  StravaDemo
//
//  Created by Jason on 6/16/25.
//

import Foundation

struct MockActivityService: ActivityService {

    func getActivities() async throws -> [Activity] {
        let now      = Date()
        let tz       = TimeZone.current
        let tzName   = tz.identifier
        let utcOff   = Double(tz.secondsFromGMT()) / 3600.0
        let startLL  = [37.7749, -122.4194]
        let endLL    = [37.7680, -122.4820]

        let run1 = Activity(
            resourceState: 2,
            name: "Morning Run in GG Park",
            distance: 6_20,
            movingTime: 1_900,
            elapsedTime: 2_050,
            totalElevationGain: 65,
            type: "Run",
            sportType: nil,
            workoutType: nil,
            id: 1_000_001,
            externalId: nil,
            uploadId: 9_000_001,
            startDate: now,
            startDateLocal: now,
            timezone: tzName,
            utcOffset: utcOff,
            startLatlng: startLL,
            endLatlng: endLL,
            locationCity: "San Francisco",
            locationState: "CA",
            locationCountry: "USA",
            achievementCount: 2,
            kudosCount: 5,
            commentCount: 1,
            athleteCount: 1,
            photoCount: 0,
            map: nil,
            trainer: false,
            commute: false,
            manual: false,
            private: false,
            flagged: false,
            gearId: nil,
            fromAcceptedTag: false,
            averageSpeed: 3.26,
            maxSpeed: 5.8,
            averageCadence: 164,
            averageWatts: nil,
            weightedAverageWatts: nil,
            kilojoules: nil,
            hasHeartrate: true,
            averageHeartrate: 147,
            maxHeartrate: 178,
            maxWatts: nil,
            prCount: 0,
            totalPhotoCount: 0,
            hasKudoed: false,
            sufferScore: 45
        )

        let ride2 = Activity(
            resourceState: 2,
            name: "Sunset Marin Headlands Ride",
            distance: 28_40,
            movingTime: 5_400,
            elapsedTime: 5_980,
            totalElevationGain: 540,
            type: "Ride",
            sportType: nil,
            workoutType: nil,
            id: 1_000_002,
            externalId: nil,
            uploadId: 9_000_002,
            startDate: now.addingTimeInterval(-86_400),
            startDateLocal: now.addingTimeInterval(-86_400),
            timezone: tzName,
            utcOffset: utcOff,
            startLatlng: startLL,
            endLatlng: endLL,
            locationCity: "Sausalito",
            locationState: "CA",
            locationCountry: "USA",
            achievementCount: 8,
            kudosCount: 12,
            commentCount: 3,
            athleteCount: 2,
            photoCount: 1,
            map: nil,
            trainer: false,
            commute: false,
            manual: false,
            private: false,
            flagged: false,
            gearId: nil,
            fromAcceptedTag: false,
            averageSpeed: 5.26,
            maxSpeed: 12.4,
            averageCadence: 88,
            averageWatts: 185,
            weightedAverageWatts: 210,
            kilojoules: 1_000,
            hasHeartrate: true,
            averageHeartrate: 152,
            maxHeartrate: 186,
            maxWatts: 650,
            prCount: 3,
            totalPhotoCount: 1,
            hasKudoed: false,
            sufferScore: 95
        )

        let walk3 = Activity(
            resourceState: 2,
            name: "Dog Walk – Embarcadero",
            distance: 3_100,
            movingTime: 2_100,
            elapsedTime: 2_400,
            totalElevationGain: 15,
            type: "Walk",
            sportType: nil,
            workoutType: nil,
            id: 1_000_003,
            externalId: nil,
            uploadId: 9_000_003,
            startDate: now.addingTimeInterval(-2 * 86_400),
            startDateLocal: now.addingTimeInterval(-2 * 86_400),
            timezone: tzName,
            utcOffset: utcOff,
            startLatlng: startLL,
            endLatlng: endLL,
            locationCity: "San Francisco",
            locationState: "CA",
            locationCountry: "USA",
            achievementCount: 0,
            kudosCount: 2,
            commentCount: 0,
            athleteCount: 1,
            photoCount: 0,
            map: nil,
            trainer: false,
            commute: false,
            manual: false,
            private: false,
            flagged: false,
            gearId: nil,
            fromAcceptedTag: false,
            averageSpeed: 1.48,
            maxSpeed: 2.1,
            averageCadence: nil,
            averageWatts: nil,
            weightedAverageWatts: nil,
            kilojoules: nil,
            hasHeartrate: false,
            averageHeartrate: nil,
            maxHeartrate: nil,
            maxWatts: nil,
            prCount: 0,
            totalPhotoCount: 0,
            hasKudoed: false,
            sufferScore: nil
        )

        let run4 = Activity(
            resourceState: 2,
            name: "Interval Track Workout",
            distance: 8_00,
            movingTime: 2_400,
            elapsedTime: 2_540,
            totalElevationGain: 10,
            type: "Run",
            sportType: nil,
            workoutType: "Intervals",
            id: 1_000_004,
            externalId: nil,
            uploadId: 9_000_004,
            startDate: now.addingTimeInterval(-3 * 86_400),
            startDateLocal: now.addingTimeInterval(-3 * 86_400),
            timezone: tzName,
            utcOffset: utcOff,
            startLatlng: startLL,
            endLatlng: endLL,
            locationCity: "San Francisco",
            locationState: "CA",
            locationCountry: "USA",
            achievementCount: 5,
            kudosCount: 9,
            commentCount: 2,
            athleteCount: 1,
            photoCount: 0,
            map: nil,
            trainer: false,
            commute: false,
            manual: false,
            private: false,
            flagged: false,
            gearId: nil,
            fromAcceptedTag: false,
            averageSpeed: 3.33,
            maxSpeed: 6.2,
            averageCadence: 172,
            averageWatts: nil,
            weightedAverageWatts: nil,
            kilojoules: nil,
            hasHeartrate: true,
            averageHeartrate: 154,
            maxHeartrate: 188,
            maxWatts: nil,
            prCount: 1,
            totalPhotoCount: 0,
            hasKudoed: false,
            sufferScore: 78
        )

        let ride5 = Activity(
            resourceState: 2,
            name: "Commute to Work",
            distance: 9_500,
            movingTime: 1_700,
            elapsedTime: 1_850,
            totalElevationGain: 120,
            type: "Ride",
            sportType: nil,
            workoutType: nil,
            id: 1_000_005,
            externalId: nil,
            uploadId: 9_000_005,
            startDate: now.addingTimeInterval(-4 * 86_400),
            startDateLocal: now.addingTimeInterval(-4 * 86_400),
            timezone: tzName,
            utcOffset: utcOff,
            startLatlng: startLL,
            endLatlng: endLL,
            locationCity: "San Francisco",
            locationState: "CA",
            locationCountry: "USA",
            achievementCount: 1,
            kudosCount: 3,
            commentCount: 0,
            athleteCount: 1,
            photoCount: 0,
            map: nil,
            trainer: false,
            commute: true,
            manual: false,
            private: false,
            flagged: false,
            gearId: nil,
            fromAcceptedTag: false,
            averageSpeed: 5.59,
            maxSpeed: 9.0,
            averageCadence: 87,
            averageWatts: 165,
            weightedAverageWatts: 185,
            kilojoules: 430,
            hasHeartrate: true,
            averageHeartrate: 140,
            maxHeartrate: 168,
            maxWatts: 510,
            prCount: 0,
            totalPhotoCount: 0,
            hasKudoed: false,
            sufferScore: 60
        )

        let walk6 = Activity(
            resourceState: 2,
            name: "Evening Walk with Friends",
            distance: 4_20,
            movingTime: 2_400,
            elapsedTime: 2_650,
            totalElevationGain: 20,
            type: "Walk",
            sportType: nil,
            workoutType: nil,
            id: 1_000_006,
            externalId: nil,
            uploadId: 9_000_006,
            startDate: now.addingTimeInterval(-5 * 86_400),
            startDateLocal: now.addingTimeInterval(-5 * 86_400),
            timezone: tzName,
            utcOffset: utcOff,
            startLatlng: startLL,
            endLatlng: endLL,
            locationCity: "San Francisco",
            locationState: "CA",
            locationCountry: "USA",
            achievementCount: 0,
            kudosCount: 1,
            commentCount: 0,
            athleteCount: 2,
            photoCount: 0,
            map: nil,
            trainer: false,
            commute: false,
            manual: false,
            private: false,
            flagged: false,
            gearId: nil,
            fromAcceptedTag: false,
            averageSpeed: 1.75,
            maxSpeed: 2.5,
            averageCadence: nil,
            averageWatts: nil,
            weightedAverageWatts: nil,
            kilojoules: nil,
            hasHeartrate: false,
            averageHeartrate: nil,
            maxHeartrate: nil,
            maxWatts: nil,
            prCount: 0,
            totalPhotoCount: 0,
            hasKudoed: false,
            sufferScore: nil
        )

        let run7 = Activity(
            resourceState: 2,
            name: "Treadmill Tempo Run",
            distance: 10_00,
            movingTime: 2_800,
            elapsedTime: 2_900,
            totalElevationGain: 0,
            type: "Run",
            sportType: nil,
            workoutType: "Tempo",
            id: 1_000_007,
            externalId: nil,
            uploadId: 9_000_007,
            startDate: now.addingTimeInterval(-6 * 86_400),
            startDateLocal: now.addingTimeInterval(-6 * 86_400),
            timezone: tzName,
            utcOffset: utcOff,
            startLatlng: nil,
            endLatlng: nil,
            locationCity: "San Francisco",
            locationState: "CA",
            locationCountry: "USA",
            achievementCount: 4,
            kudosCount: 7,
            commentCount: 1,
            athleteCount: 1,
            photoCount: 0,
            map: nil,
            trainer: true,
            commute: false,
            manual: false,
            private: false,
            flagged: false,
            gearId: nil,
            fromAcceptedTag: false,
            averageSpeed: 3.57,
            maxSpeed: 4.8,
            averageCadence: 178,
            averageWatts: nil,
            weightedAverageWatts: nil,
            kilojoules: nil,
            hasHeartrate: true,
            averageHeartrate: 160,
            maxHeartrate: 189,
            maxWatts: nil,
            prCount: 1,
            totalPhotoCount: 0,
            hasKudoed: false,
            sufferScore: 85
        )

        let ride8 = Activity(
            resourceState: 2,
            name: "Lunch Spin – Turbo Trainer",
            distance: 15_00,
            movingTime: 3_000,
            elapsedTime: 3_100,
            totalElevationGain: 0,
            type: "Ride",
            sportType: nil,
            workoutType: "Indoor",
            id: 1_000_008,
            externalId: nil,
            uploadId: 9_000_008,
            startDate: now.addingTimeInterval(-7 * 86_400),
            startDateLocal: now.addingTimeInterval(-7 * 86_400),
            timezone: tzName,
            utcOffset: utcOff,
            startLatlng: nil,
            endLatlng: nil,
            locationCity: nil,
            locationState: nil,
            locationCountry: nil,
            achievementCount: 2,
            kudosCount: 4,
            commentCount: 0,
            athleteCount: 1,
            photoCount: 0,
            map: nil,
            trainer: true,
            commute: false,
            manual: false,
            private: false,
            flagged: false,
            gearId: nil,
            fromAcceptedTag: false,
            averageSpeed: 5.0,
            maxSpeed: 8.0,
            averageCadence: 90,
            averageWatts: 200,
            weightedAverageWatts: 220,
            kilojoules: 660,
            hasHeartrate: true,
            averageHeartrate: 150,
            maxHeartrate: 180,
            maxWatts: 700,
            prCount: 0,
            totalPhotoCount: 0,
            hasKudoed: false,
            sufferScore: 70
        )

        let walk9 = Activity(
            resourceState: 2,
            name: "Beach Walk – Ocean Beach",
            distance: 4_800,
            movingTime: 2_600,
            elapsedTime: 2_900,
            totalElevationGain: 5,
            type: "Walk",
            sportType: nil,
            workoutType: nil,
            id: 1_000_009,
            externalId: nil,
            uploadId: 9_000_009,
            startDate: now.addingTimeInterval(-8 * 86_400),
            startDateLocal: now.addingTimeInterval(-8 * 86_400),
            timezone: tzName,
            utcOffset: utcOff,
            startLatlng: startLL,
            endLatlng: endLL,
            locationCity: "San Francisco",
            locationState: "CA",
            locationCountry: "USA",
            achievementCount: 0,
            kudosCount: 2,
            commentCount: 0,
            athleteCount: 1,
            photoCount: 0,
            map: nil,
            trainer: false,
            commute: false,
            manual: false,
            private: false,
            flagged: false,
            gearId: nil,
            fromAcceptedTag: false,
            averageSpeed: 1.85,
            maxSpeed: 2.6,
            averageCadence: nil,
            averageWatts: nil,
            weightedAverageWatts: nil,
            kilojoules: nil,
            hasHeartrate: false,
            averageHeartrate: nil,
            maxHeartrate: nil,
            maxWatts: nil,
            prCount: 0,
            totalPhotoCount: 0,
            hasKudoed: false,
            sufferScore: nil
        )

        let run10 = Activity(
            resourceState: 2,
            name: "5 km Recovery Jog",
            distance: 5_000,
            movingTime: 1_700,
            elapsedTime: 1_770,
            totalElevationGain: 30,
            type: "Run",
            sportType: nil,
            workoutType: "Recovery",
            id: 1_000_010,
            externalId: nil,
            uploadId: 9_000_010,
            startDate: now.addingTimeInterval(-9 * 86_400),
            startDateLocal: now.addingTimeInterval(-9 * 86_400),
            timezone: tzName,
            utcOffset: utcOff,
            startLatlng: startLL,
            endLatlng: endLL,
            locationCity: "San Francisco",
            locationState: "CA",
            locationCountry: "USA",
            achievementCount: 1,
            kudosCount: 3,
            commentCount: 0,
            athleteCount: 1,
            photoCount: 0,
            map: nil,
            trainer: false,
            commute: false,
            manual: false,
            private: false,
            flagged: false,
            gearId: nil,
            fromAcceptedTag: false,
            averageSpeed: 2.94,
            maxSpeed: 4.5,
            averageCadence: 168,
            averageWatts: nil,
            weightedAverageWatts: nil,
            kilojoules: nil,
            hasHeartrate: true,
            averageHeartrate: 135,
            maxHeartrate: 160,
            maxWatts: nil,
            prCount: 0,
            totalPhotoCount: 0,
            hasKudoed: false,
            sufferScore: 40
        )

        // Return the discrete list
        return [
            run1,
            ride2,
            walk3,
            run4,
            ride5,
            walk6,
            run7,
            ride8,
            walk9,
            run10
        ]
    }
}
